---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: ControlPlane
metadata:
  name: botanist
  namespace: shoot--core--aws-01
spec:
  type: aws
  dns:
    api: api.aws-01.core.example.com
  infrastructureProviderStatus:
    apiVersion: aws.cloud.gardener.cloud/v1beta1
    vpcID: vpc-1234
    nodesRoleARN: huasdoasdm
    instanceProfileName: foo
    keyName: bar
    subnets:
    - zone: eu-west-1
      id: subnet-acbd1234
    securityGroup: sg-xyz12345
  region: eu-west-1
  secretRef:
    name: my-aws-credentials
status:
  observedGeneration: 4
  state: |
    base64(state)
  kubernetes:
    apiServerConfig:
      environment: {}
      additionalParameters: []
    cloudProviderConfig: |
      some config
    controllerManagerConfig:
      environment: {}
      configureRoutes: true
      additionalParameters: []
    schedulerConfig:
      additionalParameters: []
    kubelet:
      additionalParameters: []
      hostnameOverride: false
      provisionCloudProviderConfig: true
