apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: infrastructures.extensions.gardener.cloud
spec:
  group: extensions.gardener.cloud
  version: v1alpha1
  scope: Namespaced
  names:
    plural: infrastructures
    singular: infrastructure
    kind: Infrastructure
    shortNames:
    - infra
