---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: DNS
metadata:
  name: api-server
  namespace: shoot--core--aws-01
spec:
  provider: aws-route53
  domain: api.johndoe-aws.garden-dev.example.com
  target: 127.0.0.1
  hostedZoneID: AH7231HCZ82
  secretRef:
    name: my-aws-credentials
status:
  state: |
    base64(state)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: DNS
metadata:
  name: ingress
  namespace: shoot--core--aws-01
spec:
  provider: aws-route53
  domain: "*.ingress.johndoe-aws.garden-dev.example.com"
  target: 127.0.0.2
  hostedZoneID: AH7231HCZ82
  secretRef:
    name: my-aws-credentials
status:
  state: |
    base64(state)
