---
apiVersion: extensions.gardener.cloud/v1beta1
kind: EtcdBackup
metadata:
  name: etcd-backup
  namespace: shoot--core--aws-01
spec:
  cloud: AWS
  region: eu-west-1
  storageName: asdasjndasd-1293912378a-2213
  secretRef:
    name: my-aws-credentials
status:
  observedGeneration: 4
  state: |
    base64(state)
  chartValues:
    storageProvider: S3
    storageContainer: asdasjndasd-1293912378a-2213
    backupSecret: my-aws-credentials
    env:
    - name: AWS_REGION
      valueFrom:
        secretKeyRef:
          name: my-aws-credentials
          key: region
    volumeMount: []
