---
apiVersion: extensions.gardener.cloud/v1beta1
kind: Generic
metadata:
  name: service-manager
  namespace: shoot--core--aws-01
spec:
  type: AWS
  dns:
    api: api.aws-01.core.example.com
  # ingress: *.ingress.aws-01.core.example.com
  infrastructureProviderStatus:
    apiVersion: aws.cloud.gardener.cloud/v1beta1
    vpcID: vpc-1234
    nodesRoleARN: huasdoasdm
    instanceProfileName: foo
    keyName: bar
    subnets:
    - zone: eu-west-1
      id: subnet-acbd1234
    securityGroup: sg-xyz12345
  shootSpec:
    ...
status:
  state: |
    base64(state)
  providerConfig:
    ...
