---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Infrastructure
metadata:
  name: botanist
  namespace: shoot--core--aws-01
  finalizers:
  - extensions.gardener.cloud/Infrastructure.aws
spec:
  type: aws
  providerConfig:
    apiVersion: v1alpha1
    networks:
      vpc:
        cidr: 10.250.0.0/16
      internal:
      - 10.250.112.0/22
      public:
      - 10.250.96.0/22
      workers:
      - 10.250.0.0/19
    zones:
    - eu-west-1a
  dns:
    api: api.aws-01.core.example.com
  region: eu-west-1
  secretRef:
    name: my-aws-credentials
  sshPublicKey: |
    base64(key)
status:
  observedGeneration: 4
  state: |
    base64(state)
  providerStatus:
    apiVersion: v1alpha1
    vpcID: vpc-1234
    nodesRoleARN: huasdoasdm
    instanceProfileName: foo
    keyName: bar
    subnets:
    - zone: eu-west-1
      id: subnet-acbd1234
    securityGroup: sg-xyz12345
