---
apiVersion: extensions.gardener.cloud/v1beta1
kind: MachineCloudConfig
metadata:
  name: worker-pool-01
  namespace: shoot--core--aws-01
spec:
  type: CoreOS
  kubernetes:
    caCert: abcd
    cloudProviderConfig: | # optional
      base64(cloud-provider-config)
    cluster:
      dns: 100.64.0.10
      domain: cluster.local
    kubelet:
      version: v1.10.8
      parameters: []
      hostnameOverride: false
      featureGates: {}
  caBundle: | # optional
    base64(certificate)
  files:
  - path: /opt/bin/health-monitor
    permissions: 0755
    content: |
      foo-bar
  daemons:
  - name: kubelet-monitor
    command:
    - /opt/bin/health-monitor
    - kubelet
status:
  observedGeneration: 4
  cloudConfig: |
    base64(cloud-config)
