---
apiVersion: extensions.gardener.cloud/v1beta1
kind: Machines
metadata:
  name: pool-cpu-worker
  namespace: shoot--core--aws-01
spec:
  cloudConfig: |
    base64(downloader-cloud-config)
  infrastructureInfo:
    apiVersion: aws.cloud.gardener.cloud/v1beta1
    vpcID: vpc-1234
    nodesRoleARN: huasdoasdm
    instanceProfileName: foo
    keyName: bar
    subnets:
    - zone: eu-west-1
      id: subnet-acbd1234
    securityGroup: sg-xyz12345
  osType: CoreOS
  autoScalerMin: 2
  autoScalerMax: 2
  providerConfig:
    apiVersion: aws.cloud.gardener.cloud/v1beta1
    ami: ami-d0dcef3b
    machineType: m4.large
    volumeType: gp2
    volumeSize: 20Gi
    # zones:
    # - eu-west-1a
  region: eu-west-1
  secretRef:
    name: my-aws-credentials
status:
  state: |
    base64(state)
